from typing import Protocol, List
from domain.models.quiz import QuizQuestion, QuizAnswer, QuizResult, LeaderboardEntry, UserScores


class IQuizService(Protocol):
    def get_questions(self, genre_slug: str) -> List[QuizQuestion]: ...
    def generate_questions(self, genre_slug: str) -> None: ...
    def submit_answers(self, user_id: str, genre_slug: str, answers: List[QuizAnswer]) -> QuizResult: ...
    def get_leaderboard(self) -> List[LeaderboardEntry]: ...
    def get_user_scores(self, user_id: str) -> UserScores: ...
    def get_question_count(self, genre_slug: str) -> int: ...
    def get_poster_paths(self, titles: List[str]) -> dict: ...
    def trigger_generation(self, genre_slug: str) -> None: ...
    def prewarm(self) -> List[str]: ...
    def get_status(self) -> dict: ...
