"""add cascade delete to movie relations

Revision ID: 0dedb59ef619
Revises: 1f1910cd9b62
Create Date: 2026-04-18 15:15:11.428369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dedb59ef619'
down_revision: Union[str, Sequence[str], None] = '1f1910cd9b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('language_iso', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_iso'], ['language.iso'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'language_iso', name='movie_translation_movie_id_language_iso_key')
    )
    op.drop_table('media_language')
    op.drop_constraint(op.f('credit_movie_id_fkey'), 'credit', type_='foreignkey')
    op.create_foreign_key('credit_movie_id_fkey', 'credit', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('media_keyword_movie_id_fkey'), 'media_keyword', type_='foreignkey')
    op.create_foreign_key('media_keyword_movie_id_fkey', 'media_keyword', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('media_production_company_movie_id_fkey'), 'media_production_company', type_='foreignkey')
    op.drop_constraint(op.f('media_production_company_tv_id_fkey'), 'media_production_company', type_='foreignkey')
    op.create_foreign_key('media_production_company_movie_id_fkey', 'media_production_company', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('media_production_company_tv_id_fkey', 'media_production_company', 'tv', ['tv_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('media_production_country_movie_id_fkey'), 'media_production_country', type_='foreignkey')
    op.drop_constraint(op.f('media_production_country_tv_id_fkey'), 'media_production_country', type_='foreignkey')
    op.create_foreign_key('media_production_country_movie_id_fkey', 'media_production_country', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('media_production_country_tv_id_fkey', 'media_production_country', 'tv', ['tv_id'], ['id'], ondelete='CASCADE')
    op.add_column('movie', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('movie', 'overview')
    op.drop_column('movie', 'title')
    op.drop_column('movie', 'poster_path')
    op.drop_column('movie', 'infos_complete')
    op.drop_column('movie', 'tagline')
    op.drop_constraint(op.f('movie_movie_genre_movie_id_fkey'), 'movie_movie_genre', type_='foreignkey')
    op.create_foreign_key('movie_movie_genre_movie_id_fkey', 'movie_movie_genre', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('playlist_media_tv_id_fkey'), 'playlist_media', type_='foreignkey')
    op.drop_constraint(op.f('playlist_media_movie_id_fkey'), 'playlist_media', type_='foreignkey')
    op.create_foreign_key('playlist_media_tv_id_fkey', 'playlist_media', 'tv', ['tv_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('playlist_media_movie_id_fkey', 'playlist_media', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_media_movie_id_fkey', 'playlist_media', type_='foreignkey')
    op.drop_constraint('playlist_media_tv_id_fkey', 'playlist_media', type_='foreignkey')
    op.create_foreign_key(op.f('playlist_media_movie_id_fkey'), 'playlist_media', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('playlist_media_tv_id_fkey'), 'playlist_media', 'tv', ['tv_id'], ['id'])
    op.drop_constraint('movie_movie_genre_movie_id_fkey', 'movie_movie_genre', type_='foreignkey')
    op.create_foreign_key(op.f('movie_movie_genre_movie_id_fkey'), 'movie_movie_genre', 'movie', ['movie_id'], ['id'])
    op.add_column('movie', sa.Column('tagline', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('infos_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('movie', sa.Column('poster_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'updated_at')
    op.drop_constraint('media_production_country_tv_id_fkey', 'media_production_country', type_='foreignkey')
    op.drop_constraint('media_production_country_movie_id_fkey', 'media_production_country', type_='foreignkey')
    op.create_foreign_key(op.f('media_production_country_tv_id_fkey'), 'media_production_country', 'tv', ['tv_id'], ['id'])
    op.create_foreign_key(op.f('media_production_country_movie_id_fkey'), 'media_production_country', 'movie', ['movie_id'], ['id'])
    op.drop_constraint('media_production_company_tv_id_fkey', 'media_production_company', type_='foreignkey')
    op.drop_constraint('media_production_company_movie_id_fkey', 'media_production_company', type_='foreignkey')
    op.create_foreign_key(op.f('media_production_company_tv_id_fkey'), 'media_production_company', 'tv', ['tv_id'], ['id'])
    op.create_foreign_key(op.f('media_production_company_movie_id_fkey'), 'media_production_company', 'movie', ['movie_id'], ['id'])
    op.drop_constraint('media_keyword_movie_id_fkey', 'media_keyword', type_='foreignkey')
    op.create_foreign_key(op.f('media_keyword_movie_id_fkey'), 'media_keyword', 'movie', ['movie_id'], ['id'])
    op.drop_constraint('credit_movie_id_fkey', 'credit', type_='foreignkey')
    op.create_foreign_key(op.f('credit_movie_id_fkey'), 'credit', 'movie', ['movie_id'], ['id'])
    op.create_table('media_language',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.iso'], name=op.f('media_language_language_id_fkey')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('media_language_movie_id_fkey')),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name=op.f('media_language_tv_id_fkey'))
    )
    op.drop_table('movie_translation')
    # ### end Alembic commands ###
