"""baseline

Revision ID: 41c93823204c
Revises: 
Create Date: 2026-02-18 14:45:52.092851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c93823204c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('iso', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('iso', name='country_pkey'),
    sa.UniqueConstraint('name', name='country_name_key')
    )
    op.create_table('credit_type',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='credit_type_pkey'),
    sa.UniqueConstraint('name', name='credit_type_name_key')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='department_pkey'),
    sa.UniqueConstraint('name', name='department_name_key')
    )
    op.create_table('gender',
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('value', name='gender_pkey'),
    sa.UniqueConstraint('gender', name='gender_gender_key')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='keyword_pkey')
    )
    op.create_table('language',
    sa.Column('iso', sa.String(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('iso', name='language_pkey')
    )
    op.create_table('media_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='media_provider_pkey')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('popularity', sa.Double(precision=53), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='movie_pkey')
    )
    op.create_table('movie_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='movie_genre_pkey')
    )
    op.create_table('production_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='production_company_pkey')
    )
    op.create_table('tv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('episode_run_time', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('in_production', sa.Boolean(), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_air_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('origin_country', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('video', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tv_pkey')
    )
    op.create_table('tv_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tv_genre_pkey')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='job_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_pkey')
    )
    op.create_table('media_keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name='media_keyword_keyword_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='media_keyword_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='media_keyword_tv_id_fkey')
    )
    op.create_table('media_language',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.iso'], name='media_language_language_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='media_language_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='media_language_tv_id_fkey')
    )
    op.create_table('media_media_provider',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('media_provider_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['country.iso'], name='media_media_provider_country_fkey'),
    sa.ForeignKeyConstraint(['media_provider_id'], ['media_provider.id'], name='media_media_provider_media_provider_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='media_media_provider_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='media_media_provider_tv_id_fkey')
    )
    op.create_table('media_production_company',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['production_company.id'], name='media_production_company_company_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='media_production_company_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='media_production_company_tv_id_fkey')
    )
    op.create_table('media_production_country',
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.iso'], name='media_production_country_country_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='media_production_country_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='media_production_country_tv_id_fkey')
    )
    op.create_table('movie_movie_genre',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['movie_genre.id'], name='movie_movie_genre_genre_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_movie_genre_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name='movie_movie_genre_pkey')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('also_known_as', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('deathday', sa.Date(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('known_for_department', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gender'], ['gender.value'], name='person_gender_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_table('tv_season',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='tv_season_tv_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tv_season_pkey')
    )
    op.create_table('tv_tv_genre',
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['tv_genre.id'], name='tv_tv_genre_genre_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='tv_tv_genre_tv_id_fkey'),
    sa.PrimaryKeyConstraint('tv_id', 'genre_id', name='tv_tv_genre_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('history_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('adult_content', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_connection', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('profile_picture_path', sa.String(length=256), nullable=True, comment="Chemin vers l'image de profil de l'utilisateur"),
    sa.Column('banner_path', sa.String(length=256), nullable=True, comment="Chemin vers la bannière de l'utilisateur"),
    sa.ForeignKeyConstraint(['country'], ['country.iso'], name='user_country_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('profile_picture_path', name='user_profile_picture_path_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('friend',
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='friend_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='friend_sender_id_fkey')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='playlist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlist_pkey')
    )
    op.create_table('tv_created_by',
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='tv_created_by_person_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='tv_created_by_tv_id_fkey'),
    sa.PrimaryKeyConstraint('tv_id', 'person_id', name='tv_created_by_pkey')
    )
    op.create_table('tv_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('production_code', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('still_path', sa.String(), nullable=True),
    sa.Column('season_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['tv_season.id'], name='tv_episode_season_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tv_episode_pkey')
    )
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='Contenu du commentaire'),
    sa.Column('has_spoiler_warning', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('tv_episode_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='comment_movie_id_fkey'),
    sa.ForeignKeyConstraint(['tv_episode_id'], ['tv_episode.id'], name='comment_tv_episode_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='comment_tv_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    op.create_table('credit',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('tv_season_id', sa.String(), nullable=True),
    sa.Column('tv_episode_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='credit_job_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='credit_movie_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='credit_person_id_fkey'),
    sa.ForeignKeyConstraint(['tv_episode_id'], ['tv_episode.id'], name='credit_tv_episode_id_fkey'),
    sa.ForeignKeyConstraint(['type'], ['credit_type.id'], name='credit_type_fkey')
    )
    op.create_table('playlist_media',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('add_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='playlist_media_movie_id_fkey'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='playlist_media_playlist_id_fkey'),
    sa.ForeignKeyConstraint(['tv_id'], ['tv.id'], name='playlist_media_tv_id_fkey'),
    sa.PrimaryKeyConstraint('playlist_id', name='playlist_media_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_media')
    op.drop_table('credit')
    op.drop_table('comment')
    op.drop_table('tv_episode')
    op.drop_table('tv_created_by')
    op.drop_table('playlist')
    op.drop_table('friend')
    op.drop_table('user')
    op.drop_table('tv_tv_genre')
    op.drop_table('tv_season')
    op.drop_table('person')
    op.drop_table('movie_movie_genre')
    op.drop_table('media_production_country')
    op.drop_table('media_production_company')
    op.drop_table('media_media_provider')
    op.drop_table('media_language')
    op.drop_table('media_keyword')
    op.drop_table('job')
    op.drop_table('tv_genre')
    op.drop_table('tv')
    op.drop_table('production_company')
    op.drop_table('movie_genre')
    op.drop_table('movie')
    op.drop_table('media_provider')
    op.drop_table('language')
    op.drop_table('keyword')
    op.drop_table('gender')
    op.drop_table('department')
    op.drop_table('credit_type')
    op.drop_table('country')
    # ### end Alembic commands ###
