"""fix unique remove key

Revision ID: 68b467c2c236
Revises: b89eef48b643
Create Date: 2026-03-16 11:51:16.391151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b467c2c236'
down_revision: Union[str, Sequence[str], None] = 'b89eef48b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_banner_path_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_profile_picture_path_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_profile_picture_path_key'), 'user', ['profile_picture_path'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_banner_path_key'), 'user', ['banner_path'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
