"""add_ml_training_counter

Revision ID: 783bf5f19a75
Revises: a1c6ad2ba606
Create Date: 2026-03-31 10:37:46.462220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783bf5f19a75'
down_revision: Union[str, Sequence[str], None] = 'a1c6ad2ba606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_counter',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('new_ratings_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='ml_training_counter_pkey')
    )
    op.drop_constraint(op.f('playlist_user_id_fkey'), 'playlist', type_='foreignkey')
    op.create_foreign_key('playlist_user_id_fkey', 'playlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_user_id_fkey', 'playlist', type_='foreignkey')
    op.create_foreign_key(op.f('playlist_user_id_fkey'), 'playlist', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('ml_training_counter')
    # ### end Alembic commands ###
