"""add column infos_complet”

Revision ID: a1c6ad2ba606
Revises: a80ae1f03c33
Create Date: 2026-03-25 16:45:54.193247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c6ad2ba606'
down_revision: Union[str, Sequence[str], None] = 'a80ae1f03c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('infos_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'infos_complete')
    # ### end Alembic commands ###
