"""Add user verification

Revision ID: b89eef48b643
Revises: 41c93823204c
Create Date: 2026-03-16 11:04:14.972527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89eef48b643'
down_revision: Union[str, Sequence[str], None] = '41c93823204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verification_code_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code_token')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'password_reset_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
