"""update tv and movie relations

Revision ID: ca5ab15df850
Revises: b3c1d2e4f5a6
Create Date: 2026-10-08 16:05:15.183602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5ab15df850'
down_revision: Union[str, Sequence[str], None] = 'b3c1d2e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('credit_tv_season_id_fkey', 'credit', 'tv_season', ['tv_season_id'], ['id'])
    op.create_foreign_key('credit_tv_id_fkey', 'credit', 'tv', ['tv_id'], ['id'])
    op.create_foreign_key('media_keyword_tv_id_fkey', 'media_keyword', 'tv', ['tv_id'], ['id'])
    op.create_index('uq_playlist_media_movie', 'playlist_media', ['playlist_id', 'movie_id'], unique=True, postgresql_where=sa.text('movie_id IS NOT NULL'))
    op.create_index('uq_playlist_media_tv', 'playlist_media', ['playlist_id', 'tv_id'], unique=True, postgresql_where=sa.text('tv_id IS NOT NULL'))
    op.add_column('tv', sa.Column('type', sa.String(), nullable=True))
    op.add_column('tv', sa.Column('popularity', sa.Double(precision=53), nullable=True))
    op.add_column('tv', sa.Column('vote_average', sa.Double(precision=53), nullable=True))
    op.add_column('tv', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('tv', sa.Column('infos_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('tv', 'title')
    op.drop_column('tv', 'release_date')
    op.add_column('tv_episode', sa.Column('vote_average', sa.Double(precision=53), nullable=True))
    op.add_column('tv_episode', sa.Column('tv_id', sa.Integer(), nullable=True))
    op.add_column('tv_season', sa.Column('vote_average', sa.Double(precision=53), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_season', 'vote_average')
    op.drop_column('tv_episode', 'tv_id')
    op.drop_column('tv_episode', 'vote_average')
    op.add_column('tv', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tv', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tv', 'infos_complete')
    op.drop_column('tv', 'vote_count')
    op.drop_column('tv', 'vote_average')
    op.drop_column('tv', 'popularity')
    op.drop_column('tv', 'type')
    op.drop_index('uq_playlist_media_tv', table_name='playlist_media', postgresql_where=sa.text('tv_id IS NOT NULL'))
    op.drop_index('uq_playlist_media_movie', table_name='playlist_media', postgresql_where=sa.text('movie_id IS NOT NULL'))
    op.drop_constraint('media_keyword_tv_id_fkey', 'media_keyword', type_='foreignkey')
    op.drop_constraint('credit_tv_id_fkey', 'credit', type_='foreignkey')
    op.drop_constraint('credit_tv_season_id_fkey', 'credit', type_='foreignkey')
    # ### end Alembic commands ###
