"""ajout is_admin

Revision ID: dc1586a4b917
Revises: b3c1d2e4f5a6
Create Date: 2026-06-20 01:04:31.313047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1586a4b917'
down_revision: Union[str, Sequence[str], None] = 'b3c1d2e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_counter',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('new_ratings_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='ml_training_counter_pkey')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('genre_slug', sa.String(length=50), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_1', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_2', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_3', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='quiz_question_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_question_pkey'),
    sa.UniqueConstraint('genre_slug', 'movie_id', 'question_type', name='uq_quiz_question_slug_movie_type')
    )
    op.create_table('quiz_score',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('genre_slug', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='quiz_score_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quiz_score_pkey'),
    sa.UniqueConstraint('user_id', 'genre_slug', name='uq_quiz_score_user_genre')
    )
    op.create_table('swipe',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='swipe_movie_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='swipe_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='swipe_pkey'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_swipe_user_movie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipe')
    op.drop_table('quiz_score')
    op.drop_table('quiz_question')
    op.drop_table('ml_training_counter')
    # ### end Alembic commands ###
