"""add quiz tables

Revision ID: f54848dc27fe
Revises: 1f1910cd9b62
Create Date: 2026-04-26 15:57:40.747550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54848dc27fe'
down_revision: Union[str, Sequence[str], None] = '1f1910cd9b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('genre_slug', sa.String(length=50), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_1', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_2', sa.String(length=255), nullable=False),
    sa.Column('wrong_answer_3', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='quiz_question_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_question_pkey')
    )
    op.create_table('quiz_score',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('genre_slug', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='quiz_score_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quiz_score_pkey'),
    sa.UniqueConstraint('user_id', 'genre_slug', name='uq_quiz_score_user_genre')
    )
    op.drop_constraint(op.f('swipe_user_id_movie_id_key'), 'swipe', type_='unique')
    op.create_unique_constraint('uq_swipe_user_movie', 'swipe', ['user_id', 'movie_id'])
    op.drop_constraint(op.f('swipe_user_id_fkey'), 'swipe', type_='foreignkey')
    op.create_foreign_key('swipe_user_id_fkey', 'swipe', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('swipe_user_id_fkey', 'swipe', type_='foreignkey')
    op.create_foreign_key(op.f('swipe_user_id_fkey'), 'swipe', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_swipe_user_movie', 'swipe', type_='unique')
    op.create_unique_constraint(op.f('swipe_user_id_movie_id_key'), 'swipe', ['user_id', 'movie_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('quiz_score')
    op.drop_table('quiz_question')
    # ### end Alembic commands ###
