from typing import Protocol, List
from domain.models.quiz import QuizQuestion, LeaderboardEntry, UserScores, GenreScore


class IQuizRepository(Protocol):
    def get_questions(self, genre_slug: str, count: int) -> List[QuizQuestion]: ...
    def count_questions(self, genre_slug: str) -> int: ...
    def insert_questions(self, questions: list[dict]) -> None: ...
    def upsert_score(self, user_id: str, genre_slug: str, points: int) -> int: ...
    def get_leaderboard(self, limit: int) -> List[LeaderboardEntry]: ...
    def get_user_scores(self, user_id: str) -> UserScores: ...
    def get_questions_by_ids(self, question_ids: list[int]) -> List[QuizQuestion]: ...
    def get_directors_for_genre(self, genre_id: int, exclude_movie_id: int, limit: int) -> List[str]: ...
    def get_actors_for_genre(self, genre_id: int, exclude_movie_id: int, limit: int) -> List[str]: ...
    def get_original_titles_for_genre(self, genre_id: int, exclude_movie_id: int, limit: int) -> List[str]: ...
    def get_actors_in_film(self, movie_id: int, limit: int) -> List[str]: ...
    def get_films_not_by_director(self, genre_id: int, director_name: str, exclude_movie_id: int, limit: int) -> List[str]: ...
    def get_directors_with_films_for_genre(self, genre_id: int, min_films: int) -> List[tuple]: ...
    def get_character_credits_for_genre(self, genre_id: int, limit: int) -> List[tuple]: ...
