name: Run Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      - name: Run tests
        env:
          TMDB_BASE_URL: "https://api.themoviedb.org/3"
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python -m coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          python -m coverage report -m
